import type { EndpointDefinition, ServiceId } from "../types";

export const DEFAULT_BASE_URLS: Record<ServiceId, string> = {
  videominer: "/api/videominer",
  vimeominer: "/api/vimeominer",
  youtubeminer: "/api/youtubeminer",
};

const fullChannelTemplate = `{
  "id": "sample-channel-id",
  "name": "Sample Channel",
  "description": "Sample description",
  "createdTime": "2026-01-01T00:00:00Z",
  "videos": []
}`;

const fullVideoTemplate = `{
  "id": "sample-video-id",
  "name": "Sample Video",
  "description": "Sample video description",
  "releaseTime": "2026-01-01T00:00:00Z",
  "comments": [],
  "captions": []
}`;

const fullCommentTemplate = `{
  "id": "sample-comment-id",
  "text": "Great video",
  "createdOn": "2026-01-01T00:00:00Z",
  "author": {
    "name": "Sample User",
    "user_link": "https://example.com/sample-user",
    "picture_link": "https://example.com/sample-user.jpg"
  }
}`;

const fullCaptionTemplate = `{
  "id": "sample-caption-id",
  "name": "English captions",
  "language": "en"
}`;

const partialUpdateTemplate = `{
  "name": "Updated value",
  "description": "Optional updated description"
}`;

const partialCommentUpdateTemplate = `{
  "text": "Updated comment text",
  "createdOn": "2026-01-02T00:00:00Z"
}`;

const partialCaptionUpdateTemplate = `{
  "name": "Updated caption name",
  "language": "es"
}`;

const partialUserUpdateTemplate = `{
  "name": "Updated user name",
  "user_link": "https://example.com/new-user-link",
  "picture_link": "https://example.com/new-picture"
}`;

export const ENDPOINTS: EndpointDefinition[] = [
  {
    id: "vimeo-get-channel",
    service: "vimeominer",
    section: "ingestion",
    method: "GET",
    label: "Vimeo: get channel by ID",
    pathTemplate: "/vimeoMiner/v1/{id}",
    description:
      "Builds channel data from Vimeo without storing it in VideoMiner.",
    pathParams: ["id"],
    queryParams: [
      { name: "maxVideos", defaultValue: "10" },
      { name: "maxComments", defaultValue: "10" },
    ],
    authMode: "none",
  },
  {
    id: "vimeo-post-channel",
    service: "vimeominer",
    section: "ingestion",
    method: "POST",
    label: "Vimeo: fetch and publish channel",
    pathTemplate: "/vimeoMiner/v1/{id}",
    description:
      "Builds channel data from Vimeo and posts it to VideoMiner storage.",
    pathParams: ["id"],
    queryParams: [
      { name: "maxVideos", defaultValue: "10" },
      { name: "maxComments", defaultValue: "10" },
    ],
    authMode: "optional",
  },
  {
    id: "youtube-v1-get-channel",
    service: "youtubeminer",
    section: "ingestion",
    method: "GET",
    label: "YouTube v1: get channel by ID",
    pathTemplate: "/youTubeMiner/v1/{id}",
    description:
      "Builds channel data using search strategy without storing in VideoMiner.",
    pathParams: ["id"],
    queryParams: [
      { name: "maxVideos", defaultValue: "10" },
      { name: "maxComments", defaultValue: "10" },
    ],
    authMode: "none",
  },
  {
    id: "youtube-v1-post-channel",
    service: "youtubeminer",
    section: "ingestion",
    method: "POST",
    label: "YouTube v1: fetch and publish channel",
    pathTemplate: "/youTubeMiner/v1/{id}",
    description:
      "Builds channel data using search strategy and stores it in VideoMiner.",
    pathParams: ["id"],
    queryParams: [
      { name: "maxVideos", defaultValue: "10" },
      { name: "maxComments", defaultValue: "10" },
    ],
    authMode: "optional",
  },
  {
    id: "youtube-v1-get-channels",
    service: "youtubeminer",
    section: "ingestion",
    method: "GET",
    label: "YouTube v1: search channels",
    pathTemplate: "/youTubeMiner/v1/channels",
    description: "Searches channels by name without storing in VideoMiner.",
    queryParams: [
      { name: "name", placeholder: "music" },
      { name: "maxChannels", defaultValue: "3" },
      { name: "maxVideos", defaultValue: "10" },
      { name: "maxComments", defaultValue: "10" },
    ],
    authMode: "none",
  },
  {
    id: "youtube-v1-post-channels",
    service: "youtubeminer",
    section: "ingestion",
    method: "POST",
    label: "YouTube v1: search and publish channels",
    pathTemplate: "/youTubeMiner/v1/channels",
    description: "Searches channels by name and stores the result in VideoMiner.",
    queryParams: [
      { name: "name", placeholder: "music" },
      { name: "maxChannels", defaultValue: "3" },
      { name: "maxVideos", defaultValue: "10" },
      { name: "maxComments", defaultValue: "10" },
    ],
    authMode: "optional",
  },
  {
    id: "youtube-v2-get-channel",
    service: "youtubeminer",
    section: "ingestion",
    method: "GET",
    label: "YouTube v2: get channel by ID",
    pathTemplate: "/youTubeMiner/v2/{id}",
    description:
      "Builds channel data using uploads playlist strategy without storing.",
    pathParams: ["id"],
    queryParams: [
      { name: "maxVideos", defaultValue: "10" },
      { name: "maxComments", defaultValue: "10" },
    ],
    authMode: "none",
  },
  {
    id: "youtube-v2-post-channel",
    service: "youtubeminer",
    section: "ingestion",
    method: "POST",
    label: "YouTube v2: fetch and publish channel",
    pathTemplate: "/youTubeMiner/v2/{id}",
    description:
      "Builds channel data using uploads playlist strategy and stores it.",
    pathParams: ["id"],
    queryParams: [
      { name: "maxVideos", defaultValue: "10" },
      { name: "maxComments", defaultValue: "10" },
    ],
    authMode: "optional",
  },
  {
    id: "youtube-v2-get-channels",
    service: "youtubeminer",
    section: "ingestion",
    method: "GET",
    label: "YouTube v2: search channels",
    pathTemplate: "/youTubeMiner/v2/channels",
    description: "Searches channels (v2 strategy) by name without storing.",
    queryParams: [
      { name: "name", placeholder: "music" },
      { name: "maxChannels", defaultValue: "3" },
      { name: "maxVideos", defaultValue: "10" },
      { name: "maxComments", defaultValue: "10" },
    ],
    authMode: "none",
  },
  {
    id: "youtube-v2-post-channels",
    service: "youtubeminer",
    section: "ingestion",
    method: "POST",
    label: "YouTube v2: search and publish channels",
    pathTemplate: "/youTubeMiner/v2/channels",
    description: "Searches channels (v2) by name and stores them in VideoMiner.",
    queryParams: [
      { name: "name", placeholder: "music" },
      { name: "maxChannels", defaultValue: "3" },
      { name: "maxVideos", defaultValue: "10" },
      { name: "maxComments", defaultValue: "10" },
    ],
    authMode: "optional",
  },
  {
    id: "vm-create-token",
    service: "videominer",
    section: "storage",
    method: "POST",
    label: "VideoMiner: create token",
    pathTemplate: "/videoMiner/v1/token",
    description:
      "Issues a new internal token. Requires X-Token-Management-Key in Connection Settings.",
    authMode: "none",
    requiresManagementKey: true,
    bodyTemplate: `{"ttlHours":24}`,
  },
  {
    id: "vm-revoke-token",
    service: "videominer",
    section: "storage",
    method: "DELETE",
    label: "VideoMiner: revoke token",
    pathTemplate: "/videoMiner/v1/token/{id}",
    description:
      "Revokes a token by ID. Requires X-Token-Management-Key in Connection Settings.",
    pathParams: ["id"],
    authMode: "none",
    requiresManagementKey: true,
  },
  {
    id: "vm-list-channels",
    service: "videominer",
    section: "storage",
    method: "GET",
    label: "VideoMiner: list channels",
    pathTemplate: "/videoMiner/v1/channels",
    description:
      "Returns paginated channels. Only one filter field should be used at once.",
    queryParams: [
      { name: "page", defaultValue: "0" },
      { name: "size", defaultValue: "10" },
      { name: "id" },
      { name: "name" },
      { name: "description" },
      { name: "createdTime" },
      { name: "order", placeholder: "-createdTime" },
    ],
    authMode: "required",
  },
  {
    id: "vm-get-channel",
    service: "videominer",
    section: "storage",
    method: "GET",
    label: "VideoMiner: get channel by ID",
    pathTemplate: "/videoMiner/v1/channels/{id}",
    description: "Returns one channel by ID.",
    pathParams: ["id"],
    authMode: "required",
  },
  {
    id: "vm-create-channel",
    service: "videominer",
    section: "storage",
    method: "POST",
    label: "VideoMiner: create channel",
    pathTemplate: "/videoMiner/v1/channels",
    description: "Creates one channel.",
    authMode: "required",
    bodyTemplate: fullChannelTemplate,
  },
  {
    id: "vm-update-channel",
    service: "videominer",
    section: "storage",
    method: "PUT",
    label: "VideoMiner: update channel",
    pathTemplate: "/videoMiner/v1/channels/{id}",
    description: "Updates channel name and/or description.",
    pathParams: ["id"],
    authMode: "required",
    bodyTemplate: partialUpdateTemplate,
  },
  {
    id: "vm-delete-channel",
    service: "videominer",
    section: "storage",
    method: "DELETE",
    label: "VideoMiner: delete channel",
    pathTemplate: "/videoMiner/v1/channels/{id}",
    description: "Deletes channel and linked entities.",
    pathParams: ["id"],
    authMode: "required",
  },
  {
    id: "vm-list-videos",
    service: "videominer",
    section: "storage",
    method: "GET",
    label: "VideoMiner: list videos",
    pathTemplate: "/videoMiner/v1/videos",
    description:
      "Returns paginated videos. Only one filter field should be used at once.",
    queryParams: [
      { name: "page", defaultValue: "0" },
      { name: "size", defaultValue: "10" },
      { name: "id" },
      { name: "name" },
      { name: "description" },
      { name: "releaseTime" },
      { name: "order", placeholder: "-releaseTime" },
    ],
    authMode: "required",
  },
  {
    id: "vm-get-video",
    service: "videominer",
    section: "storage",
    method: "GET",
    label: "VideoMiner: get video by ID",
    pathTemplate: "/videoMiner/v1/videos/{id}",
    description: "Returns one video by ID.",
    pathParams: ["id"],
    authMode: "required",
  },
  {
    id: "vm-list-videos-by-channel",
    service: "videominer",
    section: "storage",
    method: "GET",
    label: "VideoMiner: list videos of channel",
    pathTemplate: "/videoMiner/v1/channels/{channelId}/videos",
    description: "Returns all videos linked to one channel.",
    pathParams: ["channelId"],
    authMode: "required",
  },
  {
    id: "vm-create-video",
    service: "videominer",
    section: "storage",
    method: "POST",
    label: "VideoMiner: add video to channel",
    pathTemplate: "/videoMiner/v1/channels/{channelId}/videos",
    description: "Adds one video into a channel.",
    pathParams: ["channelId"],
    authMode: "required",
    bodyTemplate: fullVideoTemplate,
  },
  {
    id: "vm-update-video",
    service: "videominer",
    section: "storage",
    method: "PUT",
    label: "VideoMiner: update video",
    pathTemplate: "/videoMiner/v1/videos/{id}",
    description: "Updates video name and/or description.",
    pathParams: ["id"],
    authMode: "required",
    bodyTemplate: partialUpdateTemplate,
  },
  {
    id: "vm-delete-video",
    service: "videominer",
    section: "storage",
    method: "DELETE",
    label: "VideoMiner: delete video",
    pathTemplate: "/videoMiner/v1/videos/{id}",
    description: "Deletes one video and linked comments/captions.",
    pathParams: ["id"],
    authMode: "required",
  },
  {
    id: "vm-list-comments",
    service: "videominer",
    section: "storage",
    method: "GET",
    label: "VideoMiner: list comments",
    pathTemplate: "/videoMiner/v1/comments",
    description:
      "Returns paginated comments. Only one filter field should be used at once.",
    queryParams: [
      { name: "page", defaultValue: "0" },
      { name: "size", defaultValue: "10" },
      { name: "id" },
      { name: "text" },
      { name: "createdOn" },
      { name: "order", placeholder: "-createdOn" },
    ],
    authMode: "required",
  },
  {
    id: "vm-get-comment",
    service: "videominer",
    section: "storage",
    method: "GET",
    label: "VideoMiner: get comment by ID",
    pathTemplate: "/videoMiner/v1/comments/{id}",
    description: "Returns one comment by ID.",
    pathParams: ["id"],
    authMode: "required",
  },
  {
    id: "vm-list-comments-by-video",
    service: "videominer",
    section: "storage",
    method: "GET",
    label: "VideoMiner: list comments of video",
    pathTemplate: "/videoMiner/v1/videos/{videoId}/comments",
    description: "Returns comments linked to one video.",
    pathParams: ["videoId"],
    authMode: "required",
  },
  {
    id: "vm-create-comment",
    service: "videominer",
    section: "storage",
    method: "POST",
    label: "VideoMiner: add comment to video",
    pathTemplate: "/videoMiner/v1/videos/{videoId}/comments",
    description: "Adds one comment into a video.",
    pathParams: ["videoId"],
    authMode: "required",
    bodyTemplate: fullCommentTemplate,
  },
  {
    id: "vm-update-comment",
    service: "videominer",
    section: "storage",
    method: "PUT",
    label: "VideoMiner: update comment",
    pathTemplate: "/videoMiner/v1/comments/{id}",
    description: "Updates comment text and/or createdOn.",
    pathParams: ["id"],
    authMode: "required",
    bodyTemplate: partialCommentUpdateTemplate,
  },
  {
    id: "vm-delete-comment",
    service: "videominer",
    section: "storage",
    method: "DELETE",
    label: "VideoMiner: delete comment",
    pathTemplate: "/videoMiner/v1/comments/{id}",
    description: "Deletes one comment.",
    pathParams: ["id"],
    authMode: "required",
  },
  {
    id: "vm-list-captions",
    service: "videominer",
    section: "storage",
    method: "GET",
    label: "VideoMiner: list captions",
    pathTemplate: "/videoMiner/v1/captions",
    description:
      "Returns paginated captions. Only one filter field should be used at once.",
    queryParams: [
      { name: "page", defaultValue: "0" },
      { name: "size", defaultValue: "10" },
      { name: "id" },
      { name: "name" },
      { name: "language" },
      { name: "order", placeholder: "-name" },
    ],
    authMode: "required",
  },
  {
    id: "vm-get-caption",
    service: "videominer",
    section: "storage",
    method: "GET",
    label: "VideoMiner: get caption by ID",
    pathTemplate: "/videoMiner/v1/captions/{id}",
    description: "Returns one caption by ID.",
    pathParams: ["id"],
    authMode: "required",
  },
  {
    id: "vm-list-captions-by-video",
    service: "videominer",
    section: "storage",
    method: "GET",
    label: "VideoMiner: list captions of video",
    pathTemplate: "/videoMiner/v1/videos/{videoId}/captions",
    description: "Returns captions linked to one video.",
    pathParams: ["videoId"],
    authMode: "required",
  },
  {
    id: "vm-create-caption",
    service: "videominer",
    section: "storage",
    method: "POST",
    label: "VideoMiner: add caption to video",
    pathTemplate: "/videoMiner/v1/videos/{videoId}/captions",
    description: "Adds one caption into a video.",
    pathParams: ["videoId"],
    authMode: "required",
    bodyTemplate: fullCaptionTemplate,
  },
  {
    id: "vm-update-caption",
    service: "videominer",
    section: "storage",
    method: "PUT",
    label: "VideoMiner: update caption",
    pathTemplate: "/videoMiner/v1/captions/{id}",
    description: "Updates caption name and/or language.",
    pathParams: ["id"],
    authMode: "required",
    bodyTemplate: partialCaptionUpdateTemplate,
  },
  {
    id: "vm-delete-caption",
    service: "videominer",
    section: "storage",
    method: "DELETE",
    label: "VideoMiner: delete caption",
    pathTemplate: "/videoMiner/v1/captions/{id}",
    description: "Deletes one caption.",
    pathParams: ["id"],
    authMode: "required",
  },
  {
    id: "vm-list-users",
    service: "videominer",
    section: "storage",
    method: "GET",
    label: "VideoMiner: list users",
    pathTemplate: "/videoMiner/v1/users",
    description:
      "Returns paginated users. Only one filter field should be used at once.",
    queryParams: [
      { name: "page", defaultValue: "0" },
      { name: "size", defaultValue: "10" },
      { name: "id" },
      { name: "name" },
      { name: "userLink" },
      { name: "pictureLink" },
      { name: "order", placeholder: "-id" },
    ],
    authMode: "required",
  },
  {
    id: "vm-get-user",
    service: "videominer",
    section: "storage",
    method: "GET",
    label: "VideoMiner: get user by ID",
    pathTemplate: "/videoMiner/v1/users/{id}",
    description: "Returns one user by ID.",
    pathParams: ["id"],
    authMode: "required",
  },
  {
    id: "vm-list-users-by-video",
    service: "videominer",
    section: "storage",
    method: "GET",
    label: "VideoMiner: list users of video",
    pathTemplate: "/videoMiner/v1/videos/{videoId}/users",
    description: "Returns users linked to comments in one video.",
    pathParams: ["videoId"],
    authMode: "required",
  },
  {
    id: "vm-update-user",
    service: "videominer",
    section: "storage",
    method: "PUT",
    label: "VideoMiner: update user",
    pathTemplate: "/videoMiner/v1/users/{id}",
    description: "Updates user name and links.",
    pathParams: ["id"],
    authMode: "required",
    bodyTemplate: partialUserUpdateTemplate,
  },
  {
    id: "vm-delete-user",
    service: "videominer",
    section: "storage",
    method: "DELETE",
    label: "VideoMiner: delete user",
    pathTemplate: "/videoMiner/v1/users/{id}",
    description: "Deletes one user (removing linked comment).",
    pathParams: ["id"],
    authMode: "required",
  },
];

export const ENDPOINTS_BY_ID = Object.fromEntries(
  ENDPOINTS.map((endpoint) => [endpoint.id, endpoint]),
) as Record<string, EndpointDefinition>;
