spring.application.name=YoutubeMiner
server.port=${SERVER_PORT:8082}

youtube.api.uri=${YOUTUBE_API_URI:https://youtube.googleapis.com/youtube/v3}
videoMiner.url=${VIDEOMINER_URL:http://localhost:8080/videoMiner/v1}
#To display errors
server.error.include-message=always

#Insert YoutubeAPIToken
youtube.api.token=${YOUTUBE_API_TOKEN:}
